version: "3.3"
services:
  php:
    build: .
    container_name: staing
    volumes:
      - ./www:/var/www
    environment:
      XDEBUG_MODE: develop,debug
    networks:
      - default
    user: www-data
  nginx-php:
    build:
      context: nginx
    ports:
      - "8090:80"
    volumes:
      - ./www:/var/www
    links:
      - php
networks:
  default:
    external: true
    name: mysql_develoop

