version: '3.1'

services:

  dbmysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3350:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d
    networks:
      - develoop
    cpus: 2
    mem_limit: 4096m
    environment:
      MYSQL_ROOT_PASSWORD: Test1235
networks:
  develoop:
    driver: bridge
