version: "3.3"
services:
  resapp:
    build: .
    container_name: seavices
    hostname: seavices
    ports:
      - '8080:80'
      - '8081:81'
      - '8082:82'
      - '8083:83'
    volumes:
      - ./:/var/www/html
      - ./docker/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - default 
  mailcatcher:
    image: schickling/mailcatcher
    container_name: mailcatcher
    ports:
      - 1080:1080
      - 1025:1025
networks:
  default:
    external: true
    name: mysql_develoop

